# Generated by Django 4.2 on 2024-09-15 21:30

from django.db import migrations
from home.models import LandingPage
from questions.models import QuestionListIndex

def create_question_list_index(apps, schema_editor):
    question_list_index = QuestionListIndex(
        title="Question List Index",
        slug="question-list-index",
        default_instructions="This is the default instructions for the question list index",
    )
    landing_page = LandingPage.objects.first()
    landing_page.add_child(instance=question_list_index)
    landing_page.save()


def reverse_create_question_list_index(apps, schema_editor):
    QuestionListIndex = apps.get_model("questions", "QuestionListIndex")

    QuestionListIndex.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_question_list_index, reverse_create_question_list_index),
    ]
