# Generated by Django 4.2 on 2024-09-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_questionlistindex_default_instructions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionlist",
            name="questions",
        ),
        migrations.DeleteModel(
            name="QuestionItem",
        ),
    ]
