# Generated by Django 4.2 on 2024-09-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_questionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionlistsubmission",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionlistsubmission",
            name="result",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
