# Generated by Django 4.2 on 2024-06-04 23:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_create_question_list_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionitem',
            name='question',
            field=wagtail.fields.RichTextField(max_length=255),
        ),
    ]
