# Generated by Django 4.2 on 2024-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_questionlistsubmission_finished_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionlistsubmission",
            name="answers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
