# Generated by Django 4.2 on 2024-06-04 23:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questionitem_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='questions',
            field=wagtail.fields.StreamField([('question', wagtail.blocks.PageChooserBlock(page_type=['questions.QuestionItem']))], blank=True, null=True),
        ),
    ]
