# Generated by Django 4.2 on 2024-06-24 17:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_questionitem_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionitem',
            options={'verbose_name': 'Questão'},
        ),
        migrations.AlterModelOptions(
            name='questionlist',
            options={'verbose_name': 'Lista de Questões'},
        ),
        migrations.AddField(
            model_name='questionlist',
            name='instructions',
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Instruções'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='answers',
            field=wagtail.fields.StreamField([('option', wagtail.blocks.StructBlock([('answer', wagtail.blocks.RichTextBlock()), ('is_correct', wagtail.blocks.BooleanBlock(default=False, required=False))]))], blank=True, null=True, verbose_name='Alternativas'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='question',
            field=wagtail.fields.RichTextField(max_length=255, verbose_name='Enunciado da questão'),
        ),
    ]
