# Generated by Django 4.2 on 2024-09-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_alter_questionitem_options_questionitemsubject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionlist",
            options={
                "verbose_name": "Lista de Questões",
                "verbose_name_plural": "Listas de Questões",
            },
        ),
    ]
