# Generated by Django 4.2 on 2024-06-24 17:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_questionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlistindex',
            name='default_instructions',
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Instruções padrão'),
        ),
    ]
