# Generated by Django 4.2 on 2024-06-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_questionlistsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlist',
            name='duration',
            field=models.IntegerField(default=120, verbose_name='Duração em minutos'),
        ),
    ]
