# Generated by Django 4.2 on 2024-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_questionlist_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlistsubmission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='questionlistsubmission',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
