# Generated by Django 4.2 on 2024-10-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionlist",
            name="title",
            field=models.CharField(
                default="Lista sem título", max_length=255, verbose_name="Título"
            ),
            preserve_default=False,
        ),
    ]
