# Generated by Django 4.2 on 2024-10-02 00:15

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("questions", "0002_questionlist_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionitem",
            options={"verbose_name": "Questão", "verbose_name_plural": "Questões"},
        ),
        migrations.AlterField(
            model_name="questionitem",
            name="subjects",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="questions.QuestionItemSubject",
                to="taggit.Tag",
                verbose_name="Assuntos",
            ),
        ),
    ]
