# Generated by Django 3.2.25 on 2024-06-03 23:10

from django.db import migrations
from home.models import LandingPage
from wagtail.models import Page, Site

def create_homepage(apps, schema_editor):
    site = Site.objects.all().first()


    actual_home = Page.objects.filter(slug='home').first()
    if actual_home:
        actual_home.delete()
    home = LandingPage(title='Site do Prof. Ruano', slug='home', depth=2, path='00010001', numchild=0)
    home.save()

    home_page = Page.objects.filter(slug='home').first()

    site = Site(root_page_id=home_page.id, is_default_site=True, hostname='localhost')
    site.save()

def remove_homepage(apps, schema_editor):
    LandingPage = apps.get_model('home', 'LandingPage')
    landing_page = LandingPage.objects.filter(slug='home').first()

    if landing_page:
        landing_page.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(create_homepage, remove_homepage),
    ]
