# Generated by Django 3.2.25 on 2024-06-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='heading',
        ),
    ]
