# Generated by Django 3.2.25 on 2024-06-03 21:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtailmetadata.models
from wagtail.models import Page, Site
from home.models import LandingPage

def create_homepage(apps, schema_editor):
    homepage = LandingPage(title="Site do Prof. Ruano")
    
    root = Page.get_first_root_node()
    root.add_child(instance=homepage)

    site = Site.objects.get(id=1)
    site.root_page = homepage
    site.save()

def delete_homepage(apps, schema_editor):
    LandingPage = apps.get_model("home", "LandingPage")
    homepage = LandingPage(title="Site do Prof. Ruano")
    homepage.delete()

    site = Site.objects.get(id=1)
    site.root_page = Page.objects.get(id=1)
    site.save()

class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_homepage, delete_homepage),
    ]
