# Generated by Django 3.2.25 on 2024-06-03 23:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_landingpage_menu_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='menu_top',
            field=wagtail.fields.StreamField([('menu_top', wagtail.blocks.StructBlock([('active', wagtail.blocks.BooleanBlock(default=True, label='Ativo', required=False)), ('title', wagtail.blocks.CharBlock(label='Título', required=True)), ('page', wagtail.blocks.PageChooserBlock(required=True))], required=False))], blank=True, null=True),
        ),
    ]
