# Generated by Django 4.2 on 2024-09-15 18:53

from django.db import migrations
from django.contrib.auth.models import User


def create_supersu(apps, schema_editor):
    new_user = User.objects.create_superuser(
        username="admin",
        email="admin@mail.com",
        password="admin",
    )

def remove_supersu(apps, schema_editor):
    User = apps.get_model("auth", "User")
    user = User.objects.filter(username="admin").first()

    if user:
        user.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.RunPython(create_supersu, remove_supersu),
    ]
