# Generated by Django 4.2 on 2024-10-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_superuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hintpage",
            options={"verbose_name": "Dica", "verbose_name_plural": "Dicas"},
        ),
        migrations.AlterModelOptions(
            name="landingpage",
            options={"verbose_name": "Página Inicial"},
        ),
    ]
