# Generated by Django 4.2 on 2024-09-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_create_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL do vídeo"),
        ),
    ]
