# Generated by Django 3.2.25 on 2024-06-03 23:10

from django.db import migrations
from django.contrib.sites.models import Site
from home.models import LandingPage
from wagtail.models import Page

def create_homepage(apps, schema_editor):
    LandingPage = apps.get_model('home', 'LandingPage')
    landing_page = LandingPage(title="Home", slug='home')
    root_page = Page.get_first_root_node()

    root_page.add_child(instance=landing_page)

    landing_page.save()

def remove_homepage(apps, schema_editor):
    LandingPage = apps.get_model('home', 'LandingPage')
    landing_page = LandingPage.objects.filter(slug='home').first()

    if landing_page:
        landing_page.delete()
class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_landingpage_menu_top'),
    ]

    operations = [
        migrations.RunPython(create_homepage, remove_homepage),
    ]
