# Generated by Django 4.2 on 2024-06-04 20:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('home', '0004_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hints', wagtail.fields.StreamField([('hints', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Título', required=True)), ('text', wagtail.blocks.TextBlock(label='Texto', required=True)), ('link', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
