# Generated by Django 4.2 on 2024-06-04 22:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hintspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='menu_top',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hints',
            field=wagtail.fields.StreamField([('hint', wagtail.blocks.StructBlock([('active', wagtail.blocks.BooleanBlock(label='Ativo', required=False)), ('title', wagtail.blocks.CharBlock(label='Título', required=False)), ('text', wagtail.blocks.TextBlock(label='Texto do popup', required=False)), ('link', wagtail.blocks.URLBlock(label='Link', required=False))], max_num=1, required=False))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HintsPage',
        ),
    ]
