# Generated by Django 4.2 on 2024-06-04 22:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_landingpage_menu_top_landingpage_hints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='hints',
            field=wagtail.fields.StreamField([('hint', wagtail.blocks.StructBlock([('active', wagtail.blocks.BooleanBlock(label='Ativo', required=False)), ('title', wagtail.blocks.CharBlock(label='Título', required=False)), ('description', wagtail.blocks.TextBlock(label='Descrição', required=False)), ('link', wagtail.blocks.URLBlock(label='Link', required=False))], max_num=1, required=False))], blank=True, null=True),
        ),
    ]
